# With some help from: https://gist.github.com/dgerosa/2e1f47a39180f39bde848e38243efa94

name: build
on: 
  push:
  # Run daily at midnight UTC to update from Notion
  schedule:
    - cron: '0 0 * * *'
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      refresh_cache:
        description: 'Force refresh of Notion cache'
        required: false
        default: 'false'
        type: choice
        options:
          - 'false'
          - 'true'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Edit here with the names of your latex file and directory (can use ".")
      DIR: .
      FILE: cv
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Update CV from Notion (if scheduled or manual)
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
        run: |
          if [ "${{ github.event.inputs.refresh_cache }}" = "true" ]; then
            python update_cv.py --refresh
          else
            python update_cv.py
          fi
          
      - name: Commit CV changes (if updated from Notion)
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Check if there are changes to commit
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git add cv.tex
            git commit -m "Auto-update CV from Notion [skip ci]"
            git push
          fi
          
      - name: Compile Full CV
        uses: dante-ev/latex-action@latest
        with:
          root_file: cv
          working_directory: ${{ env.DIR }}
      - name: Compile One-Page CV
        uses: dante-ev/latex-action@latest
        with:
          root_file: cv_one_page
          working_directory: ${{ env.DIR }}
      - name: move PDFs
        run: mkdir -p github_artifacts && mv ${{ env.DIR }}/cv.pdf ${{ env.DIR }}/cv_one_page.pdf ./github_artifacts/
      - name: Upload PDFs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv-pdfs
          path: ./github_artifacts
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: github_artifacts
      - name: move PDFs
        run: mkdir -p github_deploy && mv github_artifacts/cv-pdfs/* github_deploy/
      - name: deploy on orphan branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: build
          force_orphan: true
          enable_jekyll: true
  copy-index-to-build:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Copy To Branches Action
        uses: planetoftheweb/copy-to-branches@v1.3
        env:
          key: main
          files: index.html CNAME
